name: build

on:
  pull_request:
    paths-ignore:
      - docs/**
  push:
    paths-ignore:
      - docs/**

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Run NUKE
      run: ./build.ps1
      env:
        BranchSpec: ${{ github.ref }}
        BuildNumber: ${{ github.run_number }}
        ApiKey: ${{ secrets.NUGETAPIKEY }}

    - name: coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: TestResults/reports/lcov.info

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./Artifacts/*
